### ISSUE TITLE
Mavlink repo needed

### ISSUE THREAD

**Issue by Yury-MonZon** [svpcom/wfb-ng-osd#8]
Hi! What I do:
download release version from here wget https://github.com/svpcom/wfb-ng-osd/archive/refs/tags/wfb-ng-osd-23.08.zip
or git clone this repo
unzip it and cd inside
make osd

```cc -DWFB_OSD_VERSION='"23.8.0.973.35292-4548404a"' -Wall -pthread -std=gnu99 -D__GST_CAIRO__ -fPIC -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/x86_64-linux-gnu -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -c -o main.o main.c

In file included from main.c:41:

osdrender.h:20:10: fatal error: mavlink/ardupilotmega/mavlink.h: No such file or directory
   20 | #include "mavlink/ardupilotmega/mavlink.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

make: *** [Makefile:25: main.o] Error 1
```
But my ./mavlink/ folder is empty. Which repository I put there?

Thanks a lot!

**Comment by svpcom** [comment]
git submodule update --init --recursive --checkout

**Comment by svpcom** [comment]
It is github issue: https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release

**Comment by Yury-MonZon** [comment]
> git submodule update --init --recursive --checkout

This didn't help, but I've manually cloned mavlink repo and put it in place.
